spring.application.name=promotions-announcement-service

server.port=8082

spring.datasource.url=jdbc:postgresql://postgres-promos:5432/automatch_promos
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.kafka.bootstrap-servers=kafka-promos:9092
automatch.topic.producer=automatch.promotions.published
automatch.topic.consumer=automatch.interaction.created